### ISSUE TITLE
在开发机环境中，使用huggingface_hub下载一直timeout，是墙的原因么？

### ISSUE THREAD

**Issue by GitEasonXu** [InternLM/tutorial#142]
```python
import os 
from huggingface_hub import hf_hub_download  # Load model directly

hf_hub_download(repo_id="internlm/internlm-20b", filename="config.json")
```

```
Traceback (most recent call last):
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1012, in _prepare_proxy
    conn.connect()
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/urllib3/connection.py", line 374, in connect
    self._tunnel()
  File "/root/.conda/envs/internlm/lib/python3.10/http/client.py", line 921, in _tunnel
    (version, code, message) = response._read_status()
  File "/root/.conda/envs/internlm/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/root/.conda/envs/internlm/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /internlm/internlm-20b/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/code/InternLM/homework/course_2/huggingface_download.py", line 5, in <module>
    hf_hub_download(repo_id="internlm/internlm-20b", filename="config.json", cache_dir=saved_dir)
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1238, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1631, in get_hf_file_metadata
    r = _request_wrapper(
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "/root/.conda/envs/internlm/lib/python3.10/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /internlm/internlm-20b/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('timed out')))"), '(Request ID: af7451db-5de3-48cc-903f-b8ed77108e81)')
```

**Comment by MING-ZCH** [comment]
网络问题~
运行“export HF_ENDPOINT=https://hf-mirror.com” 添加镜像源就可以解决了
