### ISSUE TITLE
Huggingface部署mindsearch案例时报错

### ISSUE THREAD

**Issue by chengyingshe** [InternLM/tutorial#1854]
按照教程在Huggingface中部署mindsearch示例时报错：`ImportError: cannot import name 'AutoRegister' from 'class_registry'`，报错详情如下：
```
Exit code: 1. Reason: Traceback (most recent call last):
  File "/home/user/app/app.py", line 6, in <module>
    from lagent.schema import AgentStatusCode
  File "/usr/local/lib/python3.10/site-packages/lagent/__init__.py", line 2, in <module>
    from .actions import *  # noqa: F401, F403
  File "/usr/local/lib/python3.10/site-packages/lagent/actions/__init__.py", line 3, in <module>
    from .action_executor import ActionExecutor
  File "/usr/local/lib/python3.10/site-packages/lagent/actions/action_executor.py", line 4, in <module>
    from .base_action import BaseAction
  File "/usr/local/lib/python3.10/site-packages/lagent/actions/base_action.py", line 14, in <module>
    from class_registry import AutoRegister, ClassRegistry
ImportError: cannot import name 'AutoRegister' from 'class_registry' (/usr/local/lib/python3.10/site-packages/class_registry/__init__.py)
```

**Comment by fak111** [comment]
+1

**Comment by fak111** [comment]
已解决
在/workspaces/codespaces-blank/mindsearch/requirements.txt  加一行：class_registry==2.1.2
详情看https://blog.csdn.net/weixin_46509586/article/details/142220494?sharetype=blogdetail&sharerId=142220494&sharerefer=PC&sharesource=weixin_46509586&sharefrom=from_link

**Comment by chengyingshe** [comment]
> 已解决 在/workspaces/codespaces-blank/mindsearch/requirements.txt 加一行：class_registry==2.1.2 详情看https://blog.csdn.net/weixin_46509586/article/details/142220494?sharetype=blogdetail&sharerId=142220494&sharerefer=PC&sharesource=weixin_46509586&sharefrom=from_link
